pipeline {
    agent any
    tools {
        nodejs "node1610"
    }
    environment {
        MODE = "dev"
    }

    stages {        
        stage('pre build') {
            steps {
                sh "rm -rf ././Dockerfile"
                sh "rm -rf ././nginx.conf"
                sh "cp ./cicd/dev/Dockerfile ./Dockerfile"
                sh "cp ./cicd/dev/nginx.conf ./nginx.conf"
                script {                    
                    tag = sh(script: "git tag -l | tail -1 | tr -d \'\\n\'", returnStdout: true)
                    docker_image_name = sh(script: "echo ${env.JOB_BASE_NAME} | tr -d \'\\n\'", returnStdout: true)                     
                }                
            }
        }
        stage('print prebuild') {
            steps {                                
                echo "dockerimage:tag ${docker_image_name}:${tag}"
            }
        }
        stage('yarn install') {
            steps {
                sh "yarn install"
            }
        }
        stage('yarn build') {
            steps {
                sh "yarn build"
            }
        }
        stage('docker build and push') {
            steps {
                script {
                    docker.withRegistry("http://${REGISTRY}", "NEXUS_DOCKER_ID")  {
                        script {
                            customimage = docker.build "${docker_image_name}:${tag}"
                            customimage.push()
                            sh(script: "docker rmi ${REGISTRY}/${docker_image_name}:${tag}", returnStdout: true)
                        }
                    }
                }   
            }
        }
        stage('checkout cicd branch') {
            steps {
                git branch: 'cicd', url: 'https://github.com/srmproject/JCP-Front-Core.git'
            }
        }
        stage('change image:tag') {
            steps {
                dir("dev") {
                    sh """
                    cat <<EOF > kustomization.yaml
                    bases:
                    - ../base
                    namePrefix: dev-
                    
                    images:
                    - name: core-image
                      newName: ${docker_image_name}
                      newTag: ${tag}    
                    EOF
                    """.stripIndent()
                    
                    withCredentials([sshUserPrivateKey(credentialsId: "JCP-FRONTEND-CORE-SSHKEY", keyFileVariable: "SSH_KEY")]) {
                        sh """
                            ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
                            git add kustomization.yaml
                            git commit -m 'change image:tag'
                            git config --local user.email "myjenkins@admin.com"
                            git config --local user.name "jenkins"
                            git remote set-url target git@github.com:srmproject/JCP-Front-Core.git
                            GIT_SSH_COMMAND="ssh -i $SSH_KEY" git push target cicd                            
                        """
                    }
                }
            }
        }
    }
}
