apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-core
  labels:
    app: frontend-core
spec:
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: frontend-core
  template:
    metadata:
      labels:
        app: frontend-core
    spec:
      containers:
      - name: core
        image: core-image
        resources:
          limits:
            memory: "128Mi"
            cpu: "0.1"
        ports:
        - containerPort: 80
