apiVersion: v1
kind: PersistentVolume
metadata:
  name: frontend-core
spec:
  storageClassName: local-storage-retain
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /mnt/k8s-data/dev/jcp/frontend-core
