apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frontend-core
spec:
  storageClassName: local-storage-retain
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
